on:
  workflow_call:

jobs:
  test:
    name: "ðŸ§ª Test"
    runs-on: ubuntu-latest
    container:
      image: node:24-alpine
    steps:
      - name: "Download build-tests artifact"
        uses: actions/download-artifact@v4
        with:
          name: artifacts-tests
          path: ./test_artifacts

      - name: "ðŸ“¦ Install tools"
        run: |
          apk add --no-cache \
            'mozjs~140'      \
            'nodejs~24'      \
            openjdk21-jre    \
            php84-cli

      - name: "ðŸ§© Run tests"
        working-directory: test_artifacts
        run: |
          chmod +x ./wasm2lang_run_tests.sh
          SPIDERMONKEY_JS=/usr/bin/js140 \
          PHP_CLI=/usr/bin/php           \
          ./wasm2lang_run_tests.sh